#=========================== Filebeat inputs =============================

filebeat.inputs:
- type: log
  enabled: true
  paths:
    # - /home/jialin/go/src/mains/es/ailog-*.log
    - /data/log/bcmm/bcmm-waterlog-*
  # json.overwrite_keys: true
  json.keys_under_root: true
  close_inactive: 5m
  scan_frequency: 5s

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3
  #index.codec: best_compression
  #_source.enabled: false

#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.
setup.template:
    name: "bcmm"
    fields: "bcmm.yml"
    pattern: "bcmm-waterlog*"
    overwrite: true
    enabled: true
    settings:
      index.number_of_shards: 1
      _source.enabled: true
#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["192.168.1.125:9201"]
  # index: "bcmm-%{[beat.version]}-%{+yyyy.MM.dd}"
  # index: "bcmm-waterlog-%{+yyyy.MM}"
  index: "bcmm-waterlog-2019.7"
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

# output.console:
#     pretty: true
#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - drop_fields:
      fields: ["agent","ecs","input","log","host","prospector","beat","offset","source"]
  - decode_json_fields:
        fields: ["message"]
        process_array: true
        max_depth: 8
        overwrite_keys: true

# logging.level: warning
logging.to_files: false
logging.to_stderr: true
